- name: install apache and php for servers
  tags: apache,apache2,ubuntu
  package:
    name:
      - "{{ apache_package_name }}"
      - "{{ php_package_name }}"
    state: latest


- name: start apache server (Ubuntu)
  tags: service_task
  service:
    name: "{{ apache_service }}"
    state: started
    enabled: yes

- name: change keepalive parameter
  tags: apache,ubuntu,apache2
  lineinfile:
    path: /etc/apache2/apache2.conf
    regexp: '^KeepAliveTimeout'
    line: KeepAliveTimeout 7
  when: ansible_distribution == "Ubuntu"
  notify: restart_apache

- name: copy html file for site
  tags: apache,apache2,httpd
  copy:
    src: default_site.html
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: 0644

- name: copy script to remote server
  tags: script
  copy:
    src: script1.sh
    dest: /home/simone
    owner: root
    group: root
    mode: 0777

- name: execute script1
  command: sh /home/simone/script1.sh
