- name: install apache and php for Ubuntu servers
  tags: apache,apache2,ubuntu
  apt:
    name:
      - apache2
      - libapache2-mod-php
    state: latest
  when: ansible_distribution == "Ubuntu"

- name: install apache and php for CentOS servers
  tags: apache,centos,httpd
  dnf:
    name:
      - httpd
      - php
    state: latest
  when: ansible_distribution == "CentOS"

- name: start apache server (Ubuntu)
  tags: service_task
  service:
    name: apache2
    state: started
    enabled: yes
  when: ansible_distribution == "Ubuntu"

- name: change keepalive parameter
  tags: apache,ubuntu,apache2
  lineinfile:
    path: /etc/apache2/apache2.conf
    regexp: '^KeepAliveTimeout'
    line: KeepAliveTimeout 7
  when: ansible_distribution == "Ubuntu"
  register: httpd

- name: restart apache (Ubuntu)
  tags: apache,ubuntu,apache2
  service:
    name: apache2
    state: restarted
  when: httpd.changed

- name: copy html file for site
  tags: apache,apache2,httpd
  copy:
    src: default_site.html
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: 0644
